package com.contractly.pdf.service;

import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Text;
import com.itextpdf.layout.properties.TextAlignment;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;

/**
 * PDF generation service using iText.
 * Converts contract content into downloadable PDF documents.
 */
@Service
public class PdfGeneratorService {

    private static final Logger log = LoggerFactory.getLogger(PdfGeneratorService.class);

    /**
     * Generate a PDF from contract content.
     * Returns the PDF as a byte array.
     */
    public byte[] generateContractPdf(String title, String content, String recipientName, String signerName) {
        try (ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
            PdfWriter writer = new PdfWriter(baos);
            PdfDocument pdfDoc = new PdfDocument(writer);
            Document document = new Document(pdfDoc);

            // Title
            Paragraph titleParagraph = new Paragraph(title)
                    .setFontSize(20)
                    .setBold()
                    .setTextAlignment(TextAlignment.CENTER)
                    .setMarginBottom(20);
            document.add(titleParagraph);

            // Separator
            document.add(new Paragraph("─".repeat(60))
                    .setTextAlignment(TextAlignment.CENTER)
                    .setMarginBottom(20));

            // Content (simplified — for rich text, you'd parse HTML/JSON from TipTap)
            document.add(new Paragraph(content)
                    .setFontSize(12)
                    .setMarginBottom(30));

            // Signature section
            if (signerName != null) {
                document.add(new Paragraph("─".repeat(60))
                        .setTextAlignment(TextAlignment.CENTER)
                        .setMarginTop(40));

                document.add(new Paragraph("SIGNATURES")
                        .setFontSize(14)
                        .setBold()
                        .setMarginTop(20));

                document.add(new Paragraph()
                        .add(new Text("Signed by: ").setBold())
                        .add(new Text(signerName))
                        .setMarginTop(10));
            }

            // Footer
            document.add(new Paragraph("Generated by Contractly")
                    .setFontSize(8)
                    .setTextAlignment(TextAlignment.CENTER)
                    .setMarginTop(40));

            document.close();
            return baos.toByteArray();

        } catch (Exception e) {
            log.error("Failed to generate PDF: {}", e.getMessage());
            throw new RuntimeException("PDF generation failed", e);
        }
    }
}
