package com.contractly.pdf.service;

import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.html2pdf.HtmlConverter;
import com.itextpdf.layout.element.IBlockElement;
import com.itextpdf.layout.element.IElement;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;

/**
 * PDF generation service using iText.
 * Converts contract content into downloadable PDF documents.
 */
@Service
public class PdfGeneratorService {

    private static final Logger log = LoggerFactory.getLogger(PdfGeneratorService.class);

    /**
     * Generate a PDF from contract content.
     * Returns the PDF as a byte array.
     */
    public byte[] generateContractPdf(String title, String content, String recipientName, String signerName,
                                      String documentHash, String ipAddress, java.time.LocalDateTime signedTimestamp) {
        try (ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
            PdfWriter writer = new PdfWriter(baos);
            PdfDocument pdfDoc = new PdfDocument(writer);
            Document document = new Document(pdfDoc);

            // Title
            Paragraph titleParagraph = new Paragraph(title)
                    .setFontSize(20)
                    .setBold()
                    .setTextAlignment(TextAlignment.CENTER)
                    .setMarginBottom(20);
            document.add(titleParagraph);

            // Separator
            document.add(new Paragraph("─".repeat(60))
                    .setTextAlignment(TextAlignment.CENTER)
                    .setMarginBottom(20));

            // Content (HTML)
            if (content != null && !content.isEmpty()) {
                java.util.List<IElement> elements = HtmlConverter.convertToElements(content);
                for (IElement element : elements) {
                    if (element instanceof IBlockElement) {
                        document.add((IBlockElement) element);
                    }
                }
            }

            // Footer for main contract
            document.add(new Paragraph("Generated by Contractly")
                    .setFontSize(8)
                    .setTextAlignment(TextAlignment.CENTER)
                    .setMarginTop(40));

            // Certificate of Completion
            if (signerName != null) {
                document.add(new com.itextpdf.layout.element.AreaBreak(com.itextpdf.layout.properties.AreaBreakType.NEXT_PAGE));
                
                document.add(new Paragraph("Certificate of Completion")
                        .setFontSize(24)
                        .setBold()
                        .setTextAlignment(TextAlignment.CENTER)
                        .setMarginBottom(30));

                document.add(new Paragraph("Document Hash (SHA-256):")
                        .setBold()
                        .setFontSize(12));
                document.add(new Paragraph(documentHash != null ? documentHash : "N/A")
                        .setFontSize(10)
                        .setMarginBottom(20));

                document.add(new Paragraph("Signer Details:")
                        .setBold()
                        .setFontSize(14)
                        .setMarginBottom(10));
                
                document.add(new Paragraph("Name: " + signerName));
                document.add(new Paragraph("IP Address: " + (ipAddress != null ? ipAddress : "N/A")));
                document.add(new Paragraph("Timestamp: " + (signedTimestamp != null ? signedTimestamp.toString() : "N/A")));
                
                document.add(new Paragraph("─".repeat(60))
                        .setTextAlignment(TextAlignment.CENTER)
                        .setMarginTop(40)
                        .setMarginBottom(20));
                
                document.add(new Paragraph("This is a legally binding electronic signature in accordance with applicable laws.")
                        .setFontSize(10)
                        .setTextAlignment(TextAlignment.CENTER));
            }

            document.close();
            return baos.toByteArray();

        } catch (Exception e) {
            log.error("Failed to generate PDF: {}", e.getMessage());
            throw new RuntimeException("PDF generation failed", e);
        }
    }
}
